version: '3.5'
services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app:cached
      - pip-cache:/root/.local/share/virtualenvs/:cached
    ports:
      - 8000:8000
    depends_on:
      - db
    environment:
      DOCKER: 'true'
    stdin_open: true
    tty: true

  db:
    image: postgres
    volumes:
      - pg-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: d311mv1ertf0g3
      POSTGRES_USER: dhqgipemtbjqla
      POSTGRES_PASSWORD: 6a1567f6a97a73272713a5520e1e656ccce00faf9805a4ca16759a6806028b63

volumes:
  pip-cache: null
  pg-data: null
