# Generated by Django 3.2.9 on 2021-11-07 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20211106_1700'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdetails',
            name='boquet_info',
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_address',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='BoquetInfo',
        ),
    ]
